// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADeH60neBZjrMgDbarQsqobVnv7U4v6xY',
    appId: '1:515241872246:web:519802d53f0b8d6edb8857',
    messagingSenderId: '515241872246',
    projectId: 'gestordeextras',
    authDomain: 'gestordeextras.firebaseapp.com',
    storageBucket: 'gestordeextras.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-h80EfQtCfAB0-2-qpWXHsf1Ijcb5T8',
    appId: '1:515241872246:android:08cbb51ceb2ef394db8857',
    messagingSenderId: '515241872246',
    projectId: 'gestordeextras',
    storageBucket: 'gestordeextras.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDam1hIuGnny_0sTsRnFoEmNE0BqP1LuUE',
    appId: '1:515241872246:ios:2770df35b9cc4d6cdb8857',
    messagingSenderId: '515241872246',
    projectId: 'gestordeextras',
    storageBucket: 'gestordeextras.firebasestorage.app',
    iosBundleId: 'com.example.gestorHorasExtras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDam1hIuGnny_0sTsRnFoEmNE0BqP1LuUE',
    appId: '1:515241872246:ios:2770df35b9cc4d6cdb8857',
    messagingSenderId: '515241872246',
    projectId: 'gestordeextras',
    storageBucket: 'gestordeextras.firebasestorage.app',
    iosBundleId: 'com.example.gestorHorasExtras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADeH60neBZjrMgDbarQsqobVnv7U4v6xY',
    appId: '1:515241872246:web:e14e673ed1a13a3edb8857',
    messagingSenderId: '515241872246',
    projectId: 'gestordeextras',
    authDomain: 'gestordeextras.firebaseapp.com',
    storageBucket: 'gestordeextras.firebasestorage.app',
  );
}
